import { AccentDefinition, ThemeDefinition, ThemeSettingsState } from '@/src/shared/theme/types';

export const DEFAULT_LIGHT_THEME_ID = 'milk';
export const DEFAULT_DARK_THEME_ID = 'slate';
export const DEFAULT_ACCENT_ID = 'blue';

const buildTheme = (theme: ThemeDefinition): ThemeDefinition => theme;

export const SYSTEM_THEMES: ThemeDefinition[] = [
  buildTheme({
    id: 'slate',
    nameKey: 'themes.slate',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#0F172A',
      surface: '#1E293B',
      border: '#334155',
      switchThumb: '#F8FAFC',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textDisabled: '#94A3B8',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#F43F5E',
    },
  }),
  buildTheme({
    id: 'zinc',
    nameKey: 'themes.zinc',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#18181B',
      surface: '#27272A',
      border: '#3F3F46',
      switchThumb: '#FAFAFA',
      textPrimary: '#FAFAFA',
      textSecondary: '#D4D4D8',
      textDisabled: '#A1A1AA',
      success: '#34D399',
      warning: '#F59E0B',
      error: '#FB7185',
    },
  }),
  buildTheme({
    id: 'pitch_black',
    nameKey: 'themes.pitchBlack',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#000000',
      surface: '#0A0A0A',
      border: '#171717',
      switchThumb: '#FAFAFA',
      textPrimary: '#FAFAFA',
      textSecondary: '#D4D4D4',
      textDisabled: '#737373',
      success: '#22C55E',
      warning: '#FBBF24',
      error: '#FB7185',
    },
  }),
  buildTheme({
    id: 'twilight',
    nameKey: 'themes.twilight',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#0B1220',
      surface: '#111B2E',
      border: '#22304A',
      switchThumb: '#F5F9FF',
      textPrimary: '#F5F9FF',
      textSecondary: '#BED2F0',
      textDisabled: '#7F91B0',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#F43F5E',
    },
  }),
  buildTheme({
    id: 'crimson',
    nameKey: 'themes.crimson',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#1A0F12',
      surface: '#27161C',
      border: '#3B212A',
      switchThumb: '#FFF5F6',
      textPrimary: '#FFF5F6',
      textSecondary: '#F0C8CD',
      textDisabled: '#BC9197',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#FB7185',
    },
  }),
  buildTheme({
    id: 'cosmic',
    nameKey: 'themes.cosmic',
    kind: 'dark',
    source: 'system',
    colors: {
      background: '#0B1028',
      surface: '#141A3A',
      border: '#2A2F55',
      switchThumb: '#F5F6FF',
      textPrimary: '#F5F6FF',
      textSecondary: '#C9C9F8',
      textDisabled: '#8F90C3',
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#FB7185',
    },
    backgroundGradient: {
      start: '#0A0F2E',
      end: '#2B164D',
    },
  }),
  buildTheme({
    id: 'milk',
    nameKey: 'themes.milk',
    kind: 'light',
    source: 'system',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      border: '#E2E8F0',
      switchThumb: '#0F172A',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textDisabled: '#94A3B8',
      success: '#16A34A',
      warning: '#D97706',
      error: '#DC2626',
    },
  }),
  buildTheme({
    id: 'sandstorm',
    nameKey: 'themes.sandstorm',
    kind: 'light',
    source: 'system',
    colors: {
      background: '#F7F1E2',
      surface: '#FFF8EB',
      border: '#E6D7B8',
      switchThumb: '#3D2D1C',
      textPrimary: '#3D2D1C',
      textSecondary: '#6B563A',
      textDisabled: '#9E8A6B',
      success: '#15803D',
      warning: '#B45309',
      error: '#B91C1C',
    },
  }),
  buildTheme({
    id: 'lavender',
    nameKey: 'themes.lavender',
    kind: 'light',
    source: 'system',
    colors: {
      background: '#F6F3FF',
      surface: '#FFFFFF',
      border: '#E4DCF8',
      switchThumb: '#2E2146',
      textPrimary: '#2E2146',
      textSecondary: '#5B4D80',
      textDisabled: '#8F83B2',
      success: '#16A34A',
      warning: '#C2410C',
      error: '#BE123C',
    },
  }),
  buildTheme({
    id: 'smoke',
    nameKey: 'themes.smoke',
    kind: 'light',
    source: 'system',
    colors: {
      background: '#EFF1F3',
      surface: '#FFFFFF',
      border: '#D0D5DD',
      switchThumb: '#1F2937',
      textPrimary: '#1F2937',
      textSecondary: '#4B5563',
      textDisabled: '#9CA3AF',
      success: '#15803D',
      warning: '#B45309',
      error: '#B91C1C',
    },
  }),
  buildTheme({
    id: 'sky',
    nameKey: 'themes.sky',
    kind: 'light',
    source: 'system',
    colors: {
      background: '#EAF6FF',
      surface: '#FFFFFF',
      border: '#CDE7F9',
      switchThumb: '#10324A',
      textPrimary: '#10324A',
      textSecondary: '#356080',
      textDisabled: '#7DA3BD',
      success: '#15803D',
      warning: '#B45309',
      error: '#B91C1C',
    },
  }),
];

export const SYSTEM_ACCENTS: AccentDefinition[] = [
  { id: 'blue', nameKey: 'accents.blue', source: 'system', color: '#2563EB' },
  { id: 'red', nameKey: 'accents.red', source: 'system', color: '#DC2626' },
  { id: 'orange', nameKey: 'accents.orange', source: 'system', color: '#EA580C' },
  { id: 'yellow', nameKey: 'accents.yellow', source: 'system', color: '#CA8A04' },
  { id: 'green', nameKey: 'accents.green', source: 'system', color: '#16A34A' },
  { id: 'pink', nameKey: 'accents.pink', source: 'system', color: '#DB2777' },
  { id: 'cyan', nameKey: 'accents.cyan', source: 'system', color: '#0891B2' },
];

export function createDefaultThemeSettings(mode: ThemeSettingsState['mode'] = 'auto'): ThemeSettingsState {
  return {
    version: 1,
    mode,
    lightThemeId: DEFAULT_LIGHT_THEME_ID,
    darkThemeId: DEFAULT_DARK_THEME_ID,
    accentId: DEFAULT_ACCENT_ID,
    customThemes: [],
    customAccents: [],
  };
}
